C2drik/Jetsetter

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> Formulaire

- app/controllers/trips_controller.rb
- app/models/user.rb
- app/views/trips/destroy.html.erb
- app/views/trips/edit.html.erb
- app/views/trips/index.html.erb
- app/views/trips/new.html.erb
- app/views/trips/show.html.erb
- app/views/trips/update.html.erb
- db/seeds.rb
> Tripscontroller

- app/views/trips/index.html.erb
> correctionviewIndex

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/trips_controller.rb
- app/views/trips/edit.html.erb
- app/views/trips/new.html.erb
- app/views/trips/update.html.erb
- config/routes.rb
> ModifTrip#New#Create

- app/controllers/trips_controller.rb
- app/views/trips/show.html.erb
- db/seeds.rb
> seedsupdatebooking

- app/views/shared/_navbar.html.erb
- app/views/trips/new.html.erb
- db/seeds.rb
> Add a new button for navigation

- app/controllers/bookings_controller.rb
- app/controllers/trips_controller.rb
- app/views/trips/index.html.erb
- app/views/trips/show.html.erb
> Remove raise from bookings

- app/controllers/bookings_controller.rb
- app/controllers/trips_controller.rb
- app/models/trip.rb
- app/models/user.rb
- app/views/trips/destroy.html.erb
- app/views/trips/show.html.erb
> AddCreateToBookingsController

- app/controllers/trips_controller.rb
> RemoveMasterFromTripsController

- app/views/trips/new.html.erb
> RedirectToIndexAfterCreate

- app/views/shared/_navbar.html.erb
> Add a new Toggle Dashboard

- app/views/trips/index.html.erb
> Modify cards

- app/views/trips/show.html.erb
> RemoveEdit

- app/views/layouts/application.html.erb
- app/views/trips/show.html.erb
> BookingsControllerFake A supprimer

- app/views/trips/show.html.erb
> BookingNewProblem

- app/views/trips/index.html.erb
- app/views/trips/show.html.erb
> RemoveHTFromPrice

- config/routes.rb
> RemoveHomeFromRoot

- app/assets/stylesheets/components/_navbar.scss
- config/routes.rb
> Resized logo navbar

- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_index.scss
- app/views/dashboard/show.html.erb
@EtienneTes, j'ai besoin de ton aide Obiwan.
> Dashboard#show 2.1

- app/views/bookings/edit.html.erb
- app/views/trips/index.html.erb
Please @C2drik @EtienneTes @ArafathN
> Remove all the links

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_button.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_navbar.scss
- app/controllers/trips_controller.rb
- app/views/trips/index.html.erb
- app/views/trips/new.html.erb
- app/views/trips/show.html.erb
- config/routes.rb
- db/seeds.rb
> Trips#index

- app/models/trip.rb
> Decomment Duration From Trip

- app/assets/stylesheets/components/_card.scss
- app/views/trips/new.html.erb
> Add a new style h1

- app/controllers/dashboard_controller.rb
- app/views/dashboard/show.html.erb
- app/views/shared/_navbar.html.erb
- db/seeds.rb
> Final seed

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_card_booking.scss
- app/assets/stylesheets/components/_dashboard.scss
- app/controllers/dashboard_controller.rb
- app/views/bookings/show.html.erb
- app/views/dashboard/show.html.erb
- app/views/trips/index.html.erb
- app/views/trips/show.html.erb
- config/environments/production.rb
- config/routes.rb
Lot a of modifications for stylized our website
> Bugfix before speech
